language: node_js
before_install:
  - npm install -g grunt grunt-cli
before_script:
  - grunt coffee
node_js:
  - "0.10"
script:
  - grunt test
after_success:
  - grunt ci
notifications:
  slack:
    masuilab:p4zvcihWTFLz1KwJXYGwJgeZ
env:
  - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=4yoG9YoXQFnuOqQcEMM0Y9lea4eB7uuDq
