language: node_js
before_install:
  - npm install -g coffee-script mocha mocha-lcov-reporter blanket
before_script:
  - coffee -o ./lib -c -b ./src
node_js:
  - "0.10"
script:
  - npm run-script test-coveralls
notifications:
  slack:
    masuilab:p4zvcihWTFLz1KwJXYGwJgeZ
