language: node_js
before_install:
  - npm install -g grunt grunt-cli
before_script:
  - grunt coffee
node_js:
  - "7"
  - "10"
script:
  - grunt travis
env:
  - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=4yoG9YoXQFnuOqQcEMM0Y9lea4eB7uuDq
